name: CI

on: [push]

jobs:
  build:
    name: Node v${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.15, macos-11]
        node: [12, 14, 16]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/cache@v2
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-node-${{ matrix.node }}-modules-${{ hashFiles('package-lock.json') }}

    - run: npm install
    - run: npm test
